# Generated by Django 5.1.7 on 2025-03-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_alter_taskmodel_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
